class CmdErr(Exception): pass
class CompressErr(Exception): pass
class ColorErr(Exception): pass
class DateErr(Exception): pass
class EnvErr(Exception): pass
class FileErr(Exception): pass
class ImgErr(Exception): pass
class JsonErr(Exception): pass
class TableErr(Exception): pass
class MDErr(Exception): pass
class PathErr(Exception): pass
class StrErr(Exception): pass
class YMLErr(Exception): pass
class StaticErr(Exception): pass
class FuncErr(Exception): pass
